Repository nicorithner/futbol, pull requests merged in 2020-07, with the labels that each got.

#1 Simplecove
  test/stat_tracker_test.rb
  test/test_helper.rb
Labels: Reviewer: Arique, Writer: Nico

#2 Add stat_tracker test
  test/stat_tracker_test.rb
Labels: Reviewer: Daniel, Writer: Nico

#3 Passing code for initial design.
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/.resultset.json.lock
  coverage/assets/0.12.2/DataTables-1.10.20/images/sort_asc.png
  coverage/assets/0.12.2/DataTables-1.10.20/images/sort_asc_disabled.png
  coverage/assets/0.12.2/DataTables-1.10.20/images/sort_both.png
  coverage/assets/0.12.2/DataTables-1.10.20/images/sort_desc.png
  coverage/assets/0.12.2/DataTables-1.10.20/images/sort_desc_disabled.png
  coverage/assets/0.12.2/application.css
  coverage/assets/0.12.2/application.js
  coverage/assets/0.12.2/colorbox/border.png
  coverage/assets/0.12.2/colorbox/controls.png
  coverage/assets/0.12.2/colorbox/loading.gif
  coverage/assets/0.12.2/colorbox/loading_background.png
  coverage/assets/0.12.2/favicon_green.png
  coverage/assets/0.12.2/favicon_red.png
  coverage/assets/0.12.2/favicon_yellow.png
  coverage/assets/0.12.2/images/ui-bg_flat_0_aaaaaa_40x100.png
  coverage/assets/0.12.2/images/ui-bg_flat_75_ffffff_40x100.png
  coverage/assets/0.12.2/images/ui-bg_glass_55_fbf9ee_1x400.png
  coverage/assets/0.12.2/images/ui-bg_glass_65_ffffff_1x400.png
  coverage/assets/0.12.2/images/ui-bg_glass_75_dadada_1x400.png
  coverage/assets/0.12.2/images/ui-bg_glass_75_e6e6e6_1x400.png
  coverage/assets/0.12.2/images/ui-bg_glass_95_fef1ec_1x400.png
  coverage/assets/0.12.2/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  coverage/assets/0.12.2/images/ui-icons_222222_256x240.png
  coverage/assets/0.12.2/images/ui-icons_2e83ff_256x240.png
  coverage/assets/0.12.2/images/ui-icons_454545_256x240.png
  coverage/assets/0.12.2/images/ui-icons_888888_256x240.png
  coverage/assets/0.12.2/images/ui-icons_cd0a0a_256x240.png
  coverage/assets/0.12.2/loading.gif
  coverage/assets/0.12.2/magnify.png
  coverage/index.html
  lib/games.rb
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Nico, Writer: Arique

#4 Game teams class
  lib/game_teams.rb
  lib/stat_tracker.rb
  test/game_teams_test.rb
Labels: Bug fixed, Found a bug, Reviewer: Arique, Screen Share - Peer Review, Writer: Garret

#6 Test Helper Update
  test/game_teams_test.rb
  test/stat_tracker_test.rb
  test/test_helper.rb
Labels: Development Branch - Ready to Merge, Reviewer: Daniel, Writer: Arique

#7 Stat tracker
  Gemfile
  Gemfile.lock
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  lib/game_teams.rb
  lib/stat_tracker.rb
  lib/teams.rb
  runner.rb
  test/game_test.rb
  test/teams_test.rb
  test/test_helper.rb
Labels: Development Branch - Ready to Merge, Reviewer: Nico, Writer: Daniel

#8 Lowest total score method
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/.resultset.json.lock
  coverage/assets/0.12.2/DataTables-1.10.20/images/sort_asc.png
  coverage/assets/0.12.2/DataTables-1.10.20/images/sort_asc_disabled.png
  coverage/assets/0.12.2/DataTables-1.10.20/images/sort_both.png
  coverage/assets/0.12.2/DataTables-1.10.20/images/sort_desc.png
  coverage/assets/0.12.2/DataTables-1.10.20/images/sort_desc_disabled.png
  coverage/assets/0.12.2/application.css
  coverage/assets/0.12.2/application.js
  coverage/assets/0.12.2/colorbox/border.png
  coverage/assets/0.12.2/colorbox/controls.png
  coverage/assets/0.12.2/colorbox/loading.gif
  coverage/assets/0.12.2/colorbox/loading_background.png
  coverage/assets/0.12.2/favicon_green.png
  coverage/assets/0.12.2/favicon_red.png
  coverage/assets/0.12.2/favicon_yellow.png
  coverage/assets/0.12.2/images/ui-bg_flat_0_aaaaaa_40x100.png
  coverage/assets/0.12.2/images/ui-bg_flat_75_ffffff_40x100.png
  coverage/assets/0.12.2/images/ui-bg_glass_55_fbf9ee_1x400.png
  coverage/assets/0.12.2/images/ui-bg_glass_65_ffffff_1x400.png
  coverage/assets/0.12.2/images/ui-bg_glass_75_dadada_1x400.png
  coverage/assets/0.12.2/images/ui-bg_glass_75_e6e6e6_1x400.png
  coverage/assets/0.12.2/images/ui-bg_glass_95_fef1ec_1x400.png
  coverage/assets/0.12.2/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  coverage/assets/0.12.2/images/ui-icons_222222_256x240.png
  coverage/assets/0.12.2/images/ui-icons_2e83ff_256x240.png
  coverage/assets/0.12.2/images/ui-icons_454545_256x240.png
  coverage/assets/0.12.2/images/ui-icons_888888_256x240.png
  coverage/assets/0.12.2/images/ui-icons_cd0a0a_256x240.png
  coverage/assets/0.12.2/loading.gif
  coverage/assets/0.12.2/magnify.png
  coverage/index.html
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Nico, Writer: Arique

#10 Percentage home wins
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Daniel, Writer: Garret

#11 Percentage visitor wins
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Daniel, Writer: Garret

#9 Percentage ties
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Garret, Writer: Daniel

#14 Lowest total score
  lib/games.rb
  lib/stat_tracker.rb
Labels: Reviewer: Nico, Writer: Arique

#13 Highest total score round2
  lib/games.rb
  lib/stat_tracker.rb
Labels: Reviewer: Nico, Writer: Arique

#15 Average goals by season
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/.resultset.json.lock
  coverage/assets/0.12.2/DataTables-1.10.20/images/sort_asc.png
  coverage/assets/0.12.2/DataTables-1.10.20/images/sort_asc_disabled.png
  coverage/assets/0.12.2/DataTables-1.10.20/images/sort_both.png
  coverage/assets/0.12.2/DataTables-1.10.20/images/sort_desc.png
  coverage/assets/0.12.2/DataTables-1.10.20/images/sort_desc_disabled.png
  coverage/assets/0.12.2/application.css
  coverage/assets/0.12.2/application.js
  coverage/assets/0.12.2/colorbox/border.png
  coverage/assets/0.12.2/colorbox/controls.png
  coverage/assets/0.12.2/colorbox/loading.gif
  coverage/assets/0.12.2/colorbox/loading_background.png
  coverage/assets/0.12.2/favicon_green.png
  coverage/assets/0.12.2/favicon_red.png
  coverage/assets/0.12.2/favicon_yellow.png
  coverage/assets/0.12.2/images/ui-bg_flat_0_aaaaaa_40x100.png
  coverage/assets/0.12.2/images/ui-bg_flat_75_ffffff_40x100.png
  coverage/assets/0.12.2/images/ui-bg_glass_55_fbf9ee_1x400.png
  coverage/assets/0.12.2/images/ui-bg_glass_65_ffffff_1x400.png
  coverage/assets/0.12.2/images/ui-bg_glass_75_dadada_1x400.png
  coverage/assets/0.12.2/images/ui-bg_glass_75_e6e6e6_1x400.png
  coverage/assets/0.12.2/images/ui-bg_glass_95_fef1ec_1x400.png
  coverage/assets/0.12.2/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  coverage/assets/0.12.2/images/ui-icons_222222_256x240.png
  coverage/assets/0.12.2/images/ui-icons_2e83ff_256x240.png
  coverage/assets/0.12.2/images/ui-icons_454545_256x240.png
  coverage/assets/0.12.2/images/ui-icons_888888_256x240.png
  coverage/assets/0.12.2/images/ui-icons_cd0a0a_256x240.png
  coverage/assets/0.12.2/loading.gif
  coverage/assets/0.12.2/magnify.png
  coverage/index.html
  data/games.csv
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Daniel, Writer: Nico

#12 Average goals per game
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Arique, Writer: Nico

#18 Simplecov fix
  .gitignore
  Gemfile
Labels: Reviewer: Garret, Writer: Arique

#19 team_count and highest_scoring_home_team
  lib/stat_tracker.rb
  note.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Garret, Writer: Daniel

#17 Lowest scoring home team
  coverage/.resultset.json
  coverage/index.html
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Garret, Writer: Nico

#22 Best and worst offense
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Nico, Writer: Garret

#24 Lowest scoring visitor
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Daniel, Writer: Arique

#23 highest scoring visitor
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Daniel, Writer: Arique

#26 Worst coach
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Arique, Reviewer: Daniel, Writer: Nico

#25 Winningest coach method
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Arique, Writer: Nico

#28 Average win percentage
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Arique, Writer: Nico

#29 Most accurate team
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Nico, Writer: Garret

#30 Least accurate team
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Nico, Writer: Garret

#32 Fewest goals scored
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Nico, Writer: Garret

#31 Most goals scored
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Nico, Writer: Garret

#34 Add game test and fix the name and required files for teams test
  test/game_test.rb
  test/teams_test.rb
Labels: Reviewer: Daniel, Writer: Garret

#35 Finished methods dl
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Garret, Writer: Daniel

#38 Rival
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Writer: Arique

#39 Favorite opponent
  lib/stat_tracker.rb
  lib/teams.rb
  test/stat_tracker_test.rb
Labels: Writer: Arique

#37 Refactor gw
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Nico, Writer: Garret

#40 Refactor nr - winningest and worst
  lib/stat_tracker.rb
Labels: Reviewer: Garret, Writer: Nico

#41 Passes harness
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Arique, Writer: Daniel

#42 Refactor dl
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer: Arique, Writer: Daniel

#43 A series of unfortunate ends
  .DS_Store
  .gitignore
  Gemfile
  Gemfile.lock
  data/games.csv
  lib/game_teams.rb
  lib/games.rb
  lib/stat_tracker.rb
  lib/teams.rb
  note.rb
  runner.rb
  test/game_teams_test.rb
  test/game_test.rb
  test/stat_tracker_test.rb
  test/teams_test.rb
  test/test_helper.rb
Labels: Found a bug, Reviewer: Daniel, Writer: Arique

#45 Worst coach two
  coverage/.resultset.json~96ae778315fece10db2c0b16fa2ebe71db1a437b
  coverage/index.html~96ae778315fece10db2c0b16fa2ebe71db1a437b
  lib/stat_tracker.rb
Labels: Reviewer: Daniel, Writer: Nico

#48 Team statistics
  coverage/.resultset.json~96ae778315fece10db2c0b16fa2ebe71db1a437b
  coverage/index.html~96ae778315fece10db2c0b16fa2ebe71db1a437b
  lib/csv_data.rb
  lib/stat_tracker.rb
  lib/team_statistics.rb
  module/calculatable.rb
  runner.rb
  test/csv_data_test.rb
  test/stat_tracker_test.rb
  test/team_statistics_test.rb
  test/test_helper.rb
Labels: Reviewer: Daniel, Writer: Arique

#50 League statistics
  lib/csv_data.rb
  lib/league_statistics.rb
  lib/stat_tracker.rb
  runner.rb
  test/league_statistics_test.rb
  test/stat_tracker_test.rb
  test/test_helper.rb
Labels: Reviewer: Arique, Writer: Garret

#46 Games statistics
  Ancestry_tree.md
  lib/csv_data.rb
  lib/games_statistics.rb
  lib/stat_tracker.rb
  test/game_test.rb
  test/games_statistics_test.rb
  test/stat_tracker_test.rb
  test/test_helper.rb
Labels: Reviewer: Daniel, Writer: Nico

#53 Removes all helper method tests from stat_tracker
  lib/games.rb
  lib/team_statistics.rb
  test/csv_data_test.rb
  test/game_teams_test.rb
  test/game_test.rb
  test/stat_tracker_test.rb
  test/teams_test.rb
Labels: Reviewer: Garret, Writer: Arique

#56 Add average module to games_statistics
  lib/games_statistics.rb
Labels: Reviewer: Arique, Writer: Nico

#58 Csv reader classes
  lib/csv_data.rb
  test/csv_data_test.rb
  test/game_teams_test.rb
  test/test_helper.rb
Labels: Reviewer: Garret, Writer: Arique

#59 Teams test re set up
  test/teams_test.rb
Labels: Reviewer: Arique, Writer: Nico

#62 Remove duplicate tests
  lib/league_statistics.rb
  test/stat_tracker_test.rb
Labels: Writer: Garret
